apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leprechaun

resources:
  - secrets.yaml
  - mariadb.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
